name: "SBOM upload"
on:
  push:
    branches:
      - master
      - main
permissions:
  pull-requests: write
  contents: write
  repository-projects: write
jobs:
  sbom-upload:
    uses: qred/eed-org-workflows/.github/workflows/sbom-upload.yml@main
    secrets:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        